apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: jx
spec:
  rules:
  - host: jenkins.jx.psit.xxxxxxxx.net
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
