apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: minio.psit.xxxxxxxx.net
    http:
      paths:
      - path: /
        backend:
          serviceName: minio
          servicePort: service
